typography_spectrum: 0.6142477914690971
color:
  brandStrength: 0.903733515413478
  lightness: 0.462346970802173
  saturation: 0.26242745481431484
  rhythmicContrast: 0.5716019528917968
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
opengraph:
  appId: vegansuperyacht
layout_spectrum: 0.4016428515315056
author:
  name: AngelikA Fürstler
  email: hi@vegansuperyacht.com
  url: www.vegansuperyacht.com
name: VEGNA SUPER YACHT
